### ISSUE TITLE
已搭配好 nginx+php 运行报错

### ISSUE THREAD

**Issue by zerokos** [BANKA2017/Acsign#1]
Notice: Undefined variable: cookie1 in D:\web\nginx\html\run.php on line 26
===============================
已更新cookie,下次执行时将会继续挂机(签到不受影响)
sign:未知错误#
===============================

**Comment by BANKA2017** [comment]
正在修，今天晚些时候会有更新

**Comment by BANKA2017** [comment]
已修复
