### ISSUE TITLE
输出结果变成一行

### ISSUE THREAD

**Issue by zerokos** [BANKA2017/Acsign#3]
`echo "===============================\n>sign:{$this->sign()}\n>level:{$this->online()["level"]}\n>online:{$this->online()["duration"]}\n===============================\n`
建议这一段改成
`echo "===============================<br>>sign:{$this->sign()}<br>>level:" . $this->online()["level"] . "<br>>online:" . $this->online()["duration"] . "<br>===============================<br>";`
较好 因为html中不识别\n `只认<br>`
结果就是全部变成一行

**Comment by BANKA2017** [comment]
我还是改回txt吧......其实在我的想法里这个脚本并不是靠浏览器来触发的，而是在ssh上以“php run.php”来执行的，你可以修改后自行使用即可

**Comment by zerokos** [comment]
别啊，改txt火狐又变成下载，帐号密码不就泄漏了，建议还是html，这里还是`\n`吧

**Comment by zerokos** [comment]
@BANKA2017 对了 有没有考虑支持多个帐号同时挂机？

**Comment by BANKA2017** [comment]
不会泄漏的，因为只会下载到输出结果，你大可放心（可以自己试试嘛）
多帐号也在考虑，不过要等我有时间再做
另外ac不像bilbili直播，挂机只会送香蕉，时间也只能看个爽，这个脚本最主要功能还是签到

**Comment by zerokos** [comment]
@BANKA2017 ac挂机不涨经验值吗？才知道

**Comment by BANKA2017** [comment]
ac挂机只有前120分钟是有用的（两香蕉，10经验）http://www.acfun.cn/info/#page=experience

**Comment by BANKA2017** [comment]
已添加多帐号的支持
